# This is a basic workflow that is manually triggered

name: Deploy to Dev

# Workflow will run on push to main branch
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-to-paas-dev:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Install CloudFoundry CLI
        shell: bash
        id: install-cf-cli
        run: |
          curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&source=github" | tar -zx
          sudo mv cf /usr/local/bin

      - name: deploy to gov.uk paas
        id: deploy-to-paas
        shell: bash
        run: |
          cf api https://api.london.cloud.service.gov.uk
          cf auth "${{ secrets.CF_USER_DEV }}" "${{ secrets.CF_PASSWORD_DEV }}"
          cf target -o dfe-teacher-services -s get-help-with-remote-education-dev
          cf target
          cf push -b staticfile_buildpack -p app get-help-with-remote-education-prototype-dev-pipe
